language: python

dist: jammy

cache: pip

jobs:
  include:
    - python: "2.7"
      dist: xenial
    - python: "3.5"
    - python: "3.6"
    - python: "3.7"
    - python: "3.8"
    - python: "3.9"
    - python: "3.10-dev"
    - python: "3.11-dev"
    - python: "pypy"

before_install:
  # install test dependencies
  - pip install --upgrade pip
  - pip install --upgrade codecov
  - pip install --upgrade pytest-cov
  - pip install --upgrade responses
  - pip install --upgrade importlib-metadata

install:
  # install dependencies
  - pip install --upgrade requests
  # important: install the library itself
  - pip install --upgrade -e .

script:
  # run tests
  py.test --cov pyunsplash --cov-report term-missing --cov-report xml

after_success:
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
  # codecov  # python specific?

